---
title: "Data visualization"
author: "Erika"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# General use packages:
library(tidyverse)
library(here)
library(janitor)

# Specifically for plots:
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

# And for another dataset we'll explore:
library(gapminder)

# Spatial
#library(sf)
```

## Read in the lizard data

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(data = lizards) + 
  geom_point(aes(x = total_length, y = weight))
```

Create a histogram of total lengths for all lizards un the dataset.
```{r}
plot_1 <- ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram()

plot_1
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(shape = 18,
             size = 4,
             alpha = 0.4)
```

```{r}
ggplot(data = lizards, 
       aes(x = total_length, 
           y = weight)) +
  geom_point(aes(color = common_name, 
                 size = total_length),
             alpha = 0.5)
```

Use theme light or minimal usually

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_wrap(~common_name, scales = "free")
```

```{r}
lizard_counts <- lizards %>%
  group_by(common_name) %>%
  summarize(counts = n())
```

```{r}
ggplot(data = lizard_counts, aes(y = fct_reorder(common_name, counts), x = counts)) +
  geom_col()
```

Create scatterplots faceted by species for total length versus weight. the color and shape of points should differ vased in the species (common name). change the theme. make each faceted panel have flexible axis limits.
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name, 
                 shape = common_name)) +
  theme_minimal() +
  labs(x = "Total length (mm)",
       y = "Weight (g)",
       title = "Jornada Basin lizard sizes",
       subtitle = "All lizards follow the standard length-weight relationship, with Western Whiptails being largest",
       color = "Lizard species",
       shape = "Common name") +
  facet_wrap(~common_name, scales = "free")
```

